# =============================================================
#    ██╗  ██╗███████╗███╗   ██╗     ██╗ ██████╗ ██╗███╗   ██╗
#    ╚██╗██╔╝██╔════╝████╗  ██║     ██║██╔═══██╗██║████╗  ██║
#     ╚███╔╝ █████╗  ██╔██╗ ██║     ██║██║   ██║██║██╔██╗ ██║
#     ██╔██╗ ██╔══╝  ██║╚██╗██║██   ██║██║   ██║██║██║╚██╗██║
#    ██╔╝ ██╗███████╗██║ ╚████║╚█████╔╝╚██████╔╝██║██║ ╚████║
#    ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝ ╚════╝  ╚═════╝ ╚═╝╚═╝  ╚═══╝
# =============================================================
# Authors: XenVision, okunivaxx [TGK: t.me/xen_vision]
# XenVision © 2025, All rights reserved.
# This plugin is developed and maintained by XenVision.
# Description: Конфигурация для плагина XenJoin, позволяющая
# редактировать приветственное сообщение, или добавлять свои
# пермишены приветствий для ваших привилегий.
# -------------------------------------------------------------
# WARNING: Плагин поддерживает плейсхолдеры: %player%, %prefix%, %suffix%
# -------------------------------------------------------------

join-message: "&c&lWELCOME &8⇌ %prefix% &7%player% %suffix% &aприсоединился к серверу!" #Дефолтное сообщение о входе.

greeting-messages: # Пермишены для привилегий, можно добавить свои приветствия для различных групп.
  admin: "&c&lWELCOME &8⇌ %prefix% &7%player% %suffix% &aвернулся на сервер! Стройтесь в шеренгу!"
  curator: "&c&lWELCOME &8⇌ %prefix% &7%player% %suffix% &aзашел! Держите себя в руках!"
  moder: "&c&lWELCOME &8⇌ %prefix% &7%player% %suffix% &aзашел, порядок будет наведен!"
  vip: "&c&lWELCOME &8⇌ %prefix% &7%player% %suffix% &aна сервере! Покажите высший класс!"

preset-greetings: # Примеры приветствий для голосования.
  - "&7Добро пожаловать, &e%player%! &7Наслаждайтесь игрой!"
  - "&c&lWELCOME &8⇌ &aДобро пожаловать &r%prefix% &7%player% %suffix% &aНаслаждайтесь игрой!"
  - "&a%player%, &7добро пожаловать домой! Мы ждали вас!"
